version: 3
files:
  - pattern: ".github/workflows/*.yml"
  - pattern: "actions/*/action.yml"
  - pattern: "actions/*/*/action.yml"
  - pattern: "actions/*/*/*/action.yml"
  - pattern: "examples/*.yml"
