name: pipeline
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
permissions:
  contents: read
  packages: write
  id-token: write
  pull-requests: write
jobs:
  devsecops:
    uses: slackerwx/devsecops-pipeline/.github/workflows/pipeline.yml@d746477802a801bab9a5a20b7f8934498d234d25 # v1.0.0
    with:
      platforms: linux/amd64,linux/arm64
      build-args: |
        VERSION=${{ github.ref_name }}
      app-port: "8080"
      app-health-path: /healthz
